"""Canonical sensor definitions and per-source matchers.

Matching is language-independent: the primary layer tests patterns
against the entity registry unique_id, which is generated by source
code and never localized. A fallback layer tests object_ids for older
source versions with different unique_id schemes.

Pattern syntax (per source, ordered):
- "pattern"          -> unique_id equals pattern or ends with "_pattern"
                        or "-pattern" (case-insensitive)
- "Model:pattern"    -> same, but only on entities whose device model
                        equals Model (used for FusionSolarPlus, which
                        reuses numeric signal ids across device types
                        and sets model = "Inverter" / "Battery" /
                        "Power Sensor" / "Plant")

Verified sources:
- huawei_solar: unique_id = "{serial}_{register_name}"; register names
  from huawei-solar lib register_names.py (stable English strings).
- fusion_solar: unique_id = "fusion_solar-{id}-{sensor_id}".
- fusionsolarplus: unique_id = "{device_id}_{signal_id}" (numeric
  FusionSolar API signal ids) for devices, "{device_id}_{key}" for
  plant. Device model = device_type (hardcoded English).
Values cross-checked against a real installation dump (2026-07-06).
"""
from __future__ import annotations

from dataclasses import dataclass, field

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

from .const import (
    DEVICE_BATTERY,
    DEVICE_INVERTER,
    DEVICE_METER,
    DEVICE_PLANT,
    SOURCE_FUSION_SOLAR,
    SOURCE_FUSION_SOLAR_PLUS,
    SOURCE_HUAWEI_SOLAR,
)

HS = SOURCE_HUAWEI_SOLAR
FS = SOURCE_FUSION_SOLAR
FSP = SOURCE_FUSION_SOLAR_PLUS

# FusionSolarPlus device models (hardcoded English in FSP config flow)
INV = "Inverter"
BAT = "Battery"
PWS = "Power Sensor"
PLT = "Plant"


@dataclass(frozen=True)
class HubSensorDef:
    key: str
    name: str
    device: str
    device_class: SensorDeviceClass | None = None
    state_class: SensorStateClass | None = None
    unit: str | None = None
    icon: str | None = None
    # primary: unique_id patterns (see module docstring)
    matchers: dict[str, list[str]] = field(default_factory=dict)
    # fallback: object_id patterns (exact, then "*_pattern" suffix)
    fallbacks: dict[str, list[str]] = field(default_factory=dict)


def _power(key, name, device, matchers, fallbacks=None, icon=None):
    return HubSensorDef(
        key=key, name=name, device=device,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT, unit=UnitOfPower.WATT,
        icon=icon, matchers=matchers, fallbacks=fallbacks or {},
    )


def _energy(key, name, device, matchers, fallbacks=None, icon=None):
    return HubSensorDef(
        key=key, name=name, device=device,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        unit=UnitOfEnergy.KILO_WATT_HOUR, icon=icon,
        matchers=matchers, fallbacks=fallbacks or {},
    )


def _voltage(key, name, device, matchers, fallbacks=None):
    return HubSensorDef(
        key=key, name=name, device=device,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfElectricPotential.VOLT,
        matchers=matchers, fallbacks=fallbacks or {},
    )


def _current(key, name, device, matchers, fallbacks=None):
    return HubSensorDef(
        key=key, name=name, device=device,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfElectricCurrent.AMPERE,
        matchers=matchers, fallbacks=fallbacks or {},
    )


def _percent(key, name, device, matchers, fallbacks=None, device_class=None):
    return HubSensorDef(
        key=key, name=name, device=device, device_class=device_class,
        state_class=SensorStateClass.MEASUREMENT, unit=PERCENTAGE,
        icon=None if device_class else "mdi:percent",
        matchers=matchers, fallbacks=fallbacks or {},
    )


def _text(key, name, device, matchers, fallbacks=None, icon=None):
    return HubSensorDef(
        key=key, name=name, device=device, icon=icon,
        matchers=matchers, fallbacks=fallbacks or {},
    )


SENSOR_DEFS: list[HubSensorDef] = [
    # ------------------------------------------------------------
    # Inverter
    # ------------------------------------------------------------
    _power("pv_active_power", "PV active power", DEVICE_INVERTER, {
        HS: ["active_power"],
        FSP: [f"{INV}:10018"],
    }, fallbacks={HS: ["inverter_active_power"], FSP: ["current_active_power"]}),
    _power("pv_input_power", "PV input power", DEVICE_INVERTER, {
        HS: ["input_power"],
        FSP: [f"{PLT}:flow_solar_power"],
    }, fallbacks={HS: ["inverter_input_power"], FSP: ["flow_solar_power"]},
        icon="mdi:solar-power"),
    _energy("inverter_yield_today", "Inverter yield today", DEVICE_INVERTER, {
        HS: ["daily_yield_energy"],
        FSP: [f"{INV}:10032"],
    }, fallbacks={HS: ["inverter_daily_yield"], FSP: ["daily_energy"]}),
    _energy("inverter_yield_month", "Inverter yield this month", DEVICE_INVERTER, {
        HS: ["monthly_yield_energy"],
    }, fallbacks={HS: ["inverter_monthly_yield"]}),
    _energy("inverter_yield_year", "Inverter yield this year", DEVICE_INVERTER, {
        HS: ["yearly_yield_energy"],
    }, fallbacks={HS: ["inverter_yearly_yield"]}),
    _energy("inverter_yield_total", "Inverter yield total", DEVICE_INVERTER, {
        HS: ["accumulated_yield_energy"],
        FSP: [f"{INV}:10029"],
    }, fallbacks={HS: ["inverter_total_yield"], FSP: ["total_energy_produced"]}),
    HubSensorDef(
        key="inverter_temperature", name="Inverter temperature",
        device=DEVICE_INVERTER,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        matchers={
            HS: ["internal_temperature"],
            FSP: [f"{INV}:10023"],
        },
        fallbacks={HS: ["inverter_internal_temperature"], FSP: ["temperature"]},
    ),
    _percent("inverter_efficiency", "Inverter efficiency", DEVICE_INVERTER, {
        HS: ["efficiency"],
    }, fallbacks={HS: ["inverter_efficiency"]}),
    HubSensorDef(
        key="inverter_power_factor", name="Inverter power factor",
        device=DEVICE_INVERTER,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        matchers={
            HS: ["power_factor"],
            FSP: [f"{INV}:10020"],
        },
        fallbacks={HS: ["inverter_power_factor"], FSP: ["power_factor"]},
    ),
    HubSensorDef(
        key="inverter_reactive_power", name="Inverter reactive power",
        device=DEVICE_INVERTER,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        unit="var",
        matchers={
            HS: ["reactive_power"],
            FSP: [f"{INV}:10019"],
        },
        fallbacks={HS: ["inverter_reactive_power"], FSP: ["reactive_power"]},
    ),
    _text("inverter_status", "Inverter status", DEVICE_INVERTER, {
        HS: ["device_status"],
        FSP: [f"{INV}:10025"],
    }, fallbacks={HS: ["inverter_device_status"], FSP: ["status"]},
        icon="mdi:power-settings"),
    HubSensorDef(
        key="inverter_insulation_resistance", name="Insulation resistance",
        device=DEVICE_INVERTER,
        state_class=SensorStateClass.MEASUREMENT,
        unit="MΩ", icon="mdi:omega",
        matchers={
            HS: ["insulation_resistance"],
            FSP: [f"{INV}:10024"],
        },
        fallbacks={
            HS: ["inverter_insulation_resistance"],
            FSP: ["insulation_resistance"],
        },
    ),
    _voltage("inverter_phase_a_voltage", "Inverter phase A voltage",
             DEVICE_INVERTER, {
        HS: ["phase_a_voltage"],
        FSP: [f"{INV}:10011", f"{INV}:10008"],
    }, fallbacks={HS: ["inverter_phase_a_voltage"], FSP: ["phase_a_voltage"]}),
    _current("inverter_phase_a_current", "Inverter phase A current",
             DEVICE_INVERTER, {
        HS: ["phase_a_current"],
        FSP: [f"{INV}:10014"],
    }, fallbacks={HS: ["inverter_phase_a_current"], FSP: ["phase_a_current"]}),
    HubSensorDef(
        key="inverter_grid_frequency", name="Inverter grid frequency",
        device=DEVICE_INVERTER,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfFrequency.HERTZ,
        matchers={
            HS: ["grid_frequency"],
            FSP: [f"{INV}:10021"],
        },
        fallbacks={FSP: ["grid_frequency"]},
    ),
    # ------------------------------------------------------------
    # PV strings
    # ------------------------------------------------------------
    _voltage("pv_1_voltage", "PV string 1 voltage", DEVICE_INVERTER, {
        HS: ["pv_01_voltage"],
        FSP: [f"{INV}:11001"],
    }, fallbacks={HS: ["inverter_pv_1_voltage"], FSP: ["pv_1_input_voltage"]}),
    _current("pv_1_current", "PV string 1 current", DEVICE_INVERTER, {
        HS: ["pv_01_current"],
        FSP: [f"{INV}:11002"],
    }, fallbacks={HS: ["inverter_pv_1_current"], FSP: ["pv_1_input_current"]}),
    _power("pv_1_power", "PV string 1 power", DEVICE_INVERTER, {
        FSP: [f"{INV}:11003"],
    }, fallbacks={FSP: ["pv_1_input_power"]}, icon="mdi:solar-panel"),
    _voltage("pv_2_voltage", "PV string 2 voltage", DEVICE_INVERTER, {
        HS: ["pv_02_voltage"],
        FSP: [f"{INV}:11004"],
    }, fallbacks={HS: ["inverter_pv_2_voltage"], FSP: ["pv_2_input_voltage"]}),
    _current("pv_2_current", "PV string 2 current", DEVICE_INVERTER, {
        HS: ["pv_02_current"],
        FSP: [f"{INV}:11005"],
    }, fallbacks={HS: ["inverter_pv_2_current"], FSP: ["pv_2_input_current"]}),
    _power("pv_2_power", "PV string 2 power", DEVICE_INVERTER, {
        FSP: [f"{INV}:11006"],
    }, fallbacks={FSP: ["pv_2_input_power"]}, icon="mdi:solar-panel"),
    # ------------------------------------------------------------
    # Meter / grid
    # ------------------------------------------------------------
    _power("meter_active_power", "Meter active power", DEVICE_METER, {
        HS: ["power_meter_active_power"],
        FSP: [f"{PWS}:10004", f"{PWS}:11207", f"{PWS}:2101271"],
    }, fallbacks={HS: ["power_meter_active_power"], FSP: ["active_power"]},
        icon="mdi:transmission-tower"),
    HubSensorDef(
        key="meter_reactive_power", name="Meter reactive power",
        device=DEVICE_METER,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        unit="var",
        matchers={
            HS: ["power_meter_reactive_power"],
            FSP: [f"{PWS}:10005", f"{PWS}:11208", f"{PWS}:2101272"],
        },
        fallbacks={
            HS: ["power_meter_reactive_power"],
            FSP: ["reactive_power_2"],
        },
    ),
    HubSensorDef(
        key="meter_power_factor", name="Meter power factor",
        device=DEVICE_METER,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        matchers={
            HS: ["active_grid_power_factor"],
            FSP: [f"{PWS}:10006", f"{PWS}:10014", f"{PWS}:2101280"],
        },
        fallbacks={HS: ["power_meter_power_factor"], FSP: ["power_factor_2"]},
    ),
    _voltage("meter_voltage", "Meter voltage", DEVICE_METER, {
        HS: ["grid_a_voltage"],
        FSP: [f"{PWS}:10002", f"{PWS}:11204", f"{PWS}:2101256"],
    }, fallbacks={HS: ["power_meter_voltage"], FSP: ["phase_a_voltage_2"]}),
    _current("meter_current", "Meter current", DEVICE_METER, {
        HS: ["active_grid_a_current"],
        FSP: [f"{PWS}:10003", f"{PWS}:2101268"],
    }, fallbacks={HS: ["power_meter_current"], FSP: ["phase_a_current_2"]}),
    HubSensorDef(
        key="meter_frequency", name="Meter grid frequency",
        device=DEVICE_METER,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfFrequency.HERTZ,
        matchers={
            HS: ["active_grid_frequency"],
            FSP: [f"{PWS}:10007"],
        },
        fallbacks={HS: ["power_meter_frequency"], FSP: ["grid_frequency_2"]},
    ),
    # Verified on real data: FSP "Positive Active Energy" (10008) equals
    # HS grid_exported_energy; FSP "Negative Active Energy" (10009)
    # equals HS grid_accumulated_energy (imported).
    _energy("grid_exported_energy", "Grid exported energy", DEVICE_METER, {
        HS: ["grid_exported_energy"],
        FSP: [f"{PWS}:10008", f"{PWS}:11116"],
    }, fallbacks={HS: ["power_meter_exported"], FSP: ["positive_active_energy"]},
        icon="mdi:transmission-tower-import"),
    _energy("grid_imported_energy", "Grid imported energy", DEVICE_METER, {
        HS: ["grid_accumulated_energy"],
        FSP: [f"{PWS}:10009", f"{PWS}:11115"],
    }, fallbacks={HS: ["power_meter_consumption"], FSP: ["negative_active_energy"]},
        icon="mdi:transmission-tower-export"),
    _text("meter_status", "Meter status", DEVICE_METER, {
        HS: ["meter_status"],
        FSP: [f"{PWS}:10001"],
    }, fallbacks={HS: ["power_meter_meter_status"], FSP: ["meter_status"]},
        icon="mdi:meter-electric"),
    # ------------------------------------------------------------
    # Battery (system level)
    # ------------------------------------------------------------
    _percent("battery_soc", "Battery state of charge", DEVICE_BATTERY, {
        HS: ["storage_state_of_capacity"],
        FSP: [f"{BAT}:10006"],
    }, fallbacks={HS: ["battery_state_of_capacity"], FSP: ["state_of_charge"]},
        device_class=SensorDeviceClass.BATTERY),
    _power("battery_power", "Battery charge/discharge power", DEVICE_BATTERY, {
        HS: ["storage_charge_discharge_power"],
        FSP: [f"{BAT}:10004"],
    }, fallbacks={
        HS: ["battery_charge_discharge_power"],
        FSP: ["charge_discharge_power"],
    }, icon="mdi:battery-charging"),
    _energy("battery_charged_today", "Battery charged today", DEVICE_BATTERY, {
        HS: ["storage_current_day_charge_capacity"],
        FSP: [f"{BAT}:10001"],
    }, fallbacks={HS: ["battery_day_charge"], FSP: ["energy_charged_today"]},
        icon="mdi:battery-plus"),
    _energy("battery_discharged_today", "Battery discharged today",
            DEVICE_BATTERY, {
        HS: ["storage_current_day_discharge_capacity"],
        FSP: [f"{BAT}:10002"],
    }, fallbacks={HS: ["battery_day_discharge"], FSP: ["energy_discharged_today"]},
        icon="mdi:battery-minus"),
    _energy("battery_total_charge", "Battery total charge", DEVICE_BATTERY, {
        HS: ["storage_total_charge"],
    }, fallbacks={HS: ["battery_total_charge"]}),
    _energy("battery_total_discharge", "Battery total discharge",
            DEVICE_BATTERY, {
        HS: ["storage_total_discharge"],
    }, fallbacks={HS: ["battery_total_discharge"]}),
    _voltage("battery_bus_voltage", "Battery bus voltage", DEVICE_BATTERY, {
        HS: ["storage_bus_voltage"],
        FSP: [f"{BAT}:10005"],
    }, fallbacks={HS: ["battery_bus_voltage"], FSP: ["bus_voltage"]}),
    _current("battery_bus_current", "Battery bus current", DEVICE_BATTERY, {
        HS: ["storage_bus_current"],
        FSP: [f"{BAT}:230320461"],
    }, fallbacks={HS: ["battery_bus_current"], FSP: ["module_1_bus_current"]}),
    HubSensorDef(
        key="battery_temperature", name="Battery temperature",
        device=DEVICE_BATTERY,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        matchers={
            HS: ["storage_unit_1_battery_temperature"],
            FSP: [f"{BAT}:230320462"],
        },
        fallbacks={FSP: ["module_1_internal_temperature"]},
    ),
    _text("battery_status", "Battery status", DEVICE_BATTERY, {
        HS: ["storage_running_status"],
        FSP: [f"{BAT}:10003"],
    }, fallbacks={HS: ["battery_status"], FSP: ["operating_status"]},
        icon="mdi:battery-heart-variant"),
    _text("battery_working_mode", "Battery working mode", DEVICE_BATTERY, {
        HS: ["storage_unit_1_working_mode_b"],
        FSP: [f"{BAT}:10008"],
    }, fallbacks={FSP: ["charge_discharge_mode"]},
        icon="mdi:battery-sync"),
    HubSensorDef(
        key="battery_rated_capacity", name="Battery rated capacity",
        device=DEVICE_BATTERY,
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        unit=UnitOfEnergy.KILO_WATT_HOUR, icon="mdi:battery-high",
        matchers={
            HS: ["storage_rated_capacity"],
            FSP: [f"{BAT}:10013"],
        },
        fallbacks={FSP: ["rated_capacity"]},
    ),
    # ------------------------------------------------------------
    # Plant level
    # ------------------------------------------------------------
    _power("plant_power", "Plant realtime power", DEVICE_PLANT, {
        FS: ["realtime_power"],
        FSP: [f"{PLT}:flow_solar_power"],
    }, fallbacks={FS: ["realtime_power"], FSP: ["flow_solar_power"]},
        icon="mdi:solar-power-variant"),
    _energy("plant_energy_today", "Plant energy today", DEVICE_PLANT, {
        FS: ["total_current_day_energy"],
        FSP: [f"{PLT}:dailyEnergy"],
    }, fallbacks={FS: ["total_current_day_energy"], FSP: ["today_energy"]}),
    _energy("plant_energy_month", "Plant energy this month", DEVICE_PLANT, {
        FS: ["total_current_month_energy"],
        FSP: [f"{PLT}:monthEnergy"],
    }, fallbacks={FS: ["total_current_month_energy"], FSP: ["monthly_energy"]}),
    _energy("plant_energy_year", "Plant energy this year", DEVICE_PLANT, {
        FS: ["total_current_year_energy"],
        FSP: [f"{PLT}:yearEnergy"],
    }, fallbacks={FS: ["total_current_year_energy"], FSP: ["yearly_energy"]}),
    _energy("plant_energy_total", "Plant energy total", DEVICE_PLANT, {
        FS: ["total_lifetime_energy"],
        FSP: [f"{PLT}:cumulativeEnergy"],
    }, fallbacks={FS: ["total_lifetime_energy"], FSP: ["total_energy"]}),
    # ------------------------------------------------------------
    # Consumption / flows (FusionSolarPlus only)
    # ------------------------------------------------------------
    _energy("consumption_today", "Consumption today", DEVICE_PLANT, {
        FSP: [f"{PLT}:dailyUseEnergy"],
    }, fallbacks={FSP: ["consumption_today", "total_consumption"]},
        icon="mdi:home-lightning-bolt"),
    _energy("self_used_energy_today", "Self-used energy today", DEVICE_PLANT, {
        FSP: [f"{PLT}:totalSelfUseEnergy"],
    }, fallbacks={FSP: ["self_used_energy_today"]}, icon="mdi:home-battery"),
    _energy("pv_feed_in_energy_today", "PV feed-in energy today", DEVICE_PLANT, {
        FSP: [f"{PLT}:totalFeedInEnergy"],
    }, fallbacks={FSP: ["pv_feed_in_energy"]},
        icon="mdi:transmission-tower-import"),
    _energy("imported_grid_energy_today", "Imported grid energy today",
            DEVICE_PLANT, {
        FSP: [f"{PLT}:totalGridImportEnergy"],
    }, fallbacks={FSP: ["imported_grid_energy"]},
        icon="mdi:transmission-tower-export"),
    _percent("self_consumption_ratio", "Self-consumption ratio", DEVICE_PLANT, {
        FSP: [f"{PLT}:selfConsumptionRatio", f"{PLT}:selfUseRatio"],
    }, fallbacks={FSP: ["self_consumption_ratio"]}),
    _percent("grid_import_ratio", "Grid import ratio", DEVICE_PLANT, {
        FSP: [f"{PLT}:gridImportRatio"],
    }, fallbacks={FSP: ["grid_import_ratio"]}),
    _power("flow_battery_power", "Flow battery power", DEVICE_PLANT, {
        FSP: [f"{PLT}:flow_battery_power"],
    }, fallbacks={FSP: ["flow_battery_power"]},
        icon="mdi:battery-arrow-up-outline"),
    _power("flow_load_power", "Flow load power", DEVICE_PLANT, {
        FSP: [f"{PLT}:flow_load_power"],
    }, fallbacks={FSP: ["flow_load_power"]},
        icon="mdi:home-lightning-bolt-outline"),
    _power("flow_grid_power", "Flow grid power", DEVICE_PLANT, {
        FSP: [f"{PLT}:flow_grid_power"],
    }, fallbacks={FSP: ["flow_grid_power"]}, icon="mdi:transmission-tower"),
]

SENSOR_DEFS_BY_KEY = {d.key: d for d in SENSOR_DEFS}
